name             'template-cakephp3'
maintainer       'c-styles'
maintainer_email 'eisuke@c-styles.jp'
license          'The MIT License (MIT)'
description      ''
long_description ''
version          '0.1.0'

supports 'centos' '~>6'

depends 'selinux', '~> 0.9.0'
depends 'yum-epel', '~> 0.6.5'
depends 'yum-remi-chef', '~> 1.0.3'
depends 'mysql', '~> 6.1.2'
depends 'database', '~> 4.0.9'
depends 'mysql2_chef_gem', '~> 1.0.2'
depends 'httpd', '~> 0.3.3'
depends 'php', '~> 1.7.2'
